export const metadata = {
  title: "All Payment History",
  description: "Generated by create next app",
};

export default function AllPaymentHistoryPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="h-screen">{children}</div>;
}


