export const metadata = {
  title: "All Students",
  description: "Generated by create next app",
};

export default function AllStudentsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="h-screen">{children}</div>;
}
