export const metadata = {
  title: "Payment",
  description: "Generated by create next app",
};

export default function PaymentLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="h-screen">{children}</div>;
}
