export const metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function SignLayout({ children }: { children: React.ReactNode }) {
  return <div className="h-screen">{children}</div>;
}
