import FormHeadingContent from "@/components/FormHeadingContent";
import { AddStudentForm } from "@/components/add-student/AddStudentForm";
import PrivateRoute from "@/lib/PrivateRoute";
import React from "react";

export const metadata = {
  title: "Add Student",
  description: "Generated by create next app",
};

const AddStudentPage = async () => {

  
  return (
    <div className="">
      <div className="flex justify-center items-center text-center">
      <FormHeadingContent className="pb-5" title="Student Information" />
      </div>
      <AddStudentForm />
    </div>
  );
};

export default AddStudentPage;
