import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Providers from "@/lib/Providers";

import SideNavigationBar from "@/components/common/SideNavigationBar";
import NavigationBar from "@/components/common/NavigationBar";
import PrivateRoute from "@/lib/PrivateRoute";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Educa Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className={inter.className}>
        <PrivateRoute>
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <div className="hidden border-r bg-muted/40 md:block">
              <SideNavigationBar />
            </div>

            <div className="flex flex-col">
              <NavigationBar />
              <section className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
                {children}
              </section>
            </div>
          </div>
        </PrivateRoute>
      </div>
  );
}
