export const metadata = {
  title: "Student Details Layout",
  description: "Generated by create next app",
};

export default function StudentDetailsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
